// Philosopher portrait URLs — sourced via Wikipedia REST API
window.PHILOSOPHER_PHOTOS = {
  "가브리엘 마르셀":            "https://upload.wikimedia.org/wikipedia/en/c/c1/Gabriel_Marcel_%28c._1951%29.jpg",
  "가스통 바슐라르":            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Gaston_Bachelard.jpg/330px-Gaston_Bachelard.jpg",
  "게오르크 빌헬름 프리드리히 헤겔": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Jakob_Schlesinger_-_Hegel_1831.jpg/330px-Jakob_Schlesinger_-_Hegel_1831.jpg",
  "공자":                      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Confucius_Tang_Dynasty.jpg/330px-Confucius_Tang_Dynasty.jpg",
  "니콜라우스 쿠자누스":         "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Nicholas_of_Cusa.jpg/330px-Nicholas_of_Cusa.jpg",
  "라이너 마리아 릴케":          "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Rainer_Maria_Rilke_1900.jpg/330px-Rainer_Maria_Rilke_1900.jpg",
  "루키우스 안나이우스 세네카":    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Duble_herma_of_Socrates_and_Seneca_Antikensammlung_Berlin_07.jpg/330px-Duble_herma_of_Socrates_and_Seneca_Antikensammlung_Berlin_07.jpg",
  "루트비히 비트겐슈타인":        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ludwig_Wittgenstein_1929.jpg/330px-Ludwig_Wittgenstein_1929.jpg",
  "마르쿠스 아우렐리우스":        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/MSR-ra-61-b-1-DM.jpg/330px-MSR-ra-61-b-1-DM.jpg",
  "마르틴 부버":                "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Martin_Buber_portrait.jpg/330px-Martin_Buber_portrait.jpg",
  "마르틴 하이데거":             "https://upload.wikimedia.org/wikipedia/commons/1/12/Freiburg%2C_Z%C3%A4hringen-_Jahnhalle%2C_Prof._Martin_Heidegger_w%C3%A4hrend_eines_Vortrags_-_LABW_-_Staatsarchiv_Freiburg_W_134_Nr._023740f_%28cropped%29.jpeg",
  "마리아 삼브라노":             "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Mar%C3%ADa-Zambrano-1-e1602071174321.png/330px-Mar%C3%ADa-Zambrano-1-e1602071174321.png",
  "마이스터 에크하르트":          "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Meister_Eckhart_base_copie.jpg/330px-Meister_Eckhart_base_copie.jpg",
  "모리스 메를로-퐁티":          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Maurice_Merleau-Ponty.jpg/330px-Maurice_Merleau-Ponty.jpg",
  "모리스 블랑쇼":               "https://upload.wikimedia.org/wikipedia/en/9/93/MauriceBlanchot.jpg",
  "미셸 드 몽테뉴":              "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Portrait_of_Michel_de_Montaigne%2C_circa_unknown.jpg/330px-Portrait_of_Michel_de_Montaigne%2C_circa_unknown.jpg",
  "바뤼흐 스피노자":             "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Spinoza.jpg/330px-Spinoza.jpg",
  "버나드 윌리엄스":             "https://upload.wikimedia.org/wikipedia/en/a/a6/BernardWilliams.jpg",
  "블레즈 파스칼":               "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Blaise_Pascal_Versailles.JPG/330px-Blaise_Pascal_Versailles.JPG",
  "빅터 프랭클":                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Viktor_Frankl2.jpg/330px-Viktor_Frankl2.jpg",
  "소크라테스":                  "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Socrates_Louvre.jpg/330px-Socrates_Louvre.jpg",
  "쇠렌 키르케고르":             "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/S%C3%B8ren_Kierkegaard_%281813-1855%29_-_%28cropped%29.jpg/330px-S%C3%B8ren_Kierkegaard_%281813-1855%29_-_%28cropped%29.jpg",
  "시몬 드 보부아르":            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Simone_De_Beauvoir_%28cropped%29.jpg/330px-Simone_De_Beauvoir_%28cropped%29.jpg",
  "시몬 베유":                  "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Simone_Weil_1943.jpg/330px-Simone_Weil_1943.jpg",
  "아네트 베이어":               "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Annette_Baier_002_%28cropped%29.jpg/330px-Annette_Baier_002_%28cropped%29.jpg",
  "아니키우스 보에티우스":         "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Boethius.jpeg/330px-Boethius.jpeg",
  "아르투어 쇼펜하우어":          "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Arthur_Schopenhauer_by_J_Sch%C3%A4fer%2C_1859b.jpg/330px-Arthur_Schopenhauer_by_J_Sch%C3%A4fer%2C_1859b.jpg",
  "아리스토텔레스":               "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Aristotle_Altemps_Inv8575.jpg/330px-Aristotle_Altemps_Inv8575.jpg",
  "아우렐리우스 아우구스티누스":    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Saint_Augustine_by_Philippe_de_Champaigne.jpg/330px-Saint_Augustine_by_Philippe_de_Champaigne.jpg",
  "아이리스 머독":               "https://upload.wikimedia.org/wikipedia/en/c/cb/Iris_Murdoch.png",
  "알래스데어 매킨타이어":         "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Alasdair_MacIntyre.jpg/330px-Alasdair_MacIntyre.jpg",
  "알베르 카뮈":                "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Albert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg/330px-Albert_Camus%2C_gagnant_de_prix_Nobel%2C_portrait_en_buste%2C_pos%C3%A9_au_bureau%2C_faisant_face_%C3%A0_gauche%2C_cigarette_de_tabagisme.jpg",
  "앙리 베르그송":               "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Henri_Bergson_02.jpg/330px-Henri_Bergson_02.jpg",
  "에마뉘엘 레비나스":            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Emmanuel_Levinas.jpg/330px-Emmanuel_Levinas.jpg",
  "에밀 시오랑":                "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cioran_in_Romania.jpg/330px-Cioran_in_Romania.jpg",
  "에픽테토스":                  "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Epicteti_Enchiridion_Latinis_versibus_adumbratum_%28Oxford_1715%29_frontispiece_%28cropped%29.jpg/330px-Epicteti_Enchiridion_Latinis_versibus_adumbratum_%28Oxford_1715%29_frontispiece_%28cropped%29.jpg",
  "요한 하위징아":               "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Johan-huizinga1.jpg/330px-Johan-huizinga1.jpg",
  "월트 휘트먼":                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Walt_Whitman_-_George_Collins_Cox.jpg/330px-Walt_Whitman_-_George_Collins_Cox.jpg",
  "윌리엄 제임스":               "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/William_James_b1842c.jpg/330px-William_James_b1842c.jpg",
  "이마누엘 칸트":               "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Immanuel_Kant_-_Gemaelde_1.jpg/330px-Immanuel_Kant_-_Gemaelde_1.jpg",
  "제라 야코브":                "https://upload.wikimedia.org/wikipedia/commons/c/c7/Zara_Yaqob.jpg",
  "존 듀이":                   "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/John_Dewey_cph.3a51565.jpg/330px-John_Dewey_cph.3a51565.jpg",
  "존 키츠":                   "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/John_Keats_by_William_Hilton_circa_1822_02.jpg/330px-John_Keats_by_William_Hilton_circa_1822_02.jpg",
  "줄리아 크리스테바":            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Julia_Kristeva_%C3%A0_Paris_en_2008.jpg/330px-Julia_Kristeva_%C3%A0_Paris_en_2008.jpg",
  "지그문트 프로이트":            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Sigmund_Freud%2C_by_Max_Halberstadt_%28cropped%29.jpg/330px-Sigmund_Freud%2C_by_Max_Halberstadt_%28cropped%29.jpg",
  "카를 구스타프 융":            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/ETH-BIB-Jung%2C_Carl_Gustav_%281875-1961%29-Portrait-Portr_14163_%28cropped%29.tif/lossy-page1-330px-ETH-BIB-Jung%2C_Carl_Gustav_%281875-1961%29-Portrait-Portr_14163_%28cropped%29.tif.jpg",
  "폴 틸리히":                  "https://upload.wikimedia.org/wikipedia/en/3/38/Paul_Tillich.jpg",
  "표도르 도스토옙스키":           "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Vasily_Perov_-_%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A4.%D0%9C.%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_-_Google_Art_Project.jpg/330px-Vasily_Perov_-_%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A4.%D0%9C.%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_-_Google_Art_Project.jpg",
  "프란츠 로젠츠바이크":           "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Franz_Rosenzweig.jpg/330px-Franz_Rosenzweig.jpg",
  "프리드리히 니체":              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/330px-Nietzsche187a.jpg",
  "프리드리히 실러":              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Anton_Graff_-_Friedrich_Schiller.jpg/330px-Anton_Graff_-_Friedrich_Schiller.jpg",
  "한나 아렌트":                "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg/330px-Hannah_Arendt_auf_dem_1._Kulturkritikerkongress%2C_Barbara_Niggl_Radloff%2C_FM-2019-1-5-9-16_%28cropped%29.jpg",
  "한스 게오르크 가다머":          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Hans-Georg_Gadamer.jpg/330px-Hans-Georg_Gadamer.jpg",
  "해리 프랭크퍼트":             "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Harry_Frankfurt_at_2017_ACLS_Annual_Meeting.jpg/330px-Harry_Frankfurt_at_2017_ACLS_Annual_Meeting.jpg",
  "헤라클레이토스":               "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Heraclitus_b_4_compressed.jpg/330px-Heraclitus_b_4_compressed.jpg",
  "헨리 데이비드 소로":           "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Benjamin_D._Maxham_-_Henry_David_Thoreau_-_Restored.jpg/330px-Benjamin_D._Maxham_-_Henry_David_Thoreau_-_Restored.jpg",
};
